require: 'rubocop-rspec'

AllCops:
  Include:
    - '**/*.rake'
    - '**/Gemfile'
    - '**/Rakefile'

AbcSize:
  Max: 20

Metrics/LineLength:
  Max: 100

RSpec/ExampleLength:
  Max: 10

Style/FrozenStringLiteralComment:
  Enabled: false


Style/FileName:
  Exclude:
    - 'infinum-accounts.gemspec'
